name: enclave
on:
  push:
    paths:
      - 'enclave/**'
  pull_request:
    paths:
      - 'enclave/**'

jobs:
  make_test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/enclave
        with:
          target: check clippy test
