name: enclave
description: run a Makefile target in the enclave directory
inputs:
  target:
    description: Makefile targets to run
runs:
  using: docker
  image: '../../../enclave/docker/Dockerfile'
  entrypoint: /bin/bash
  args:
    - "-c"
    - "mkdir -p /github/workspace/enclave/build && cp -a /github/workspace/enclave /home/rust/src && rm -r /home/rust/src/build && ln -s /github/workspace/enclave/build /home/rust/src/build && HOME=/home/rust && make -C /home/rust/src/ ${{ inputs.target }}"
